### ISSUE TITLE
[Bug] Cannot cancel incoming call.

### ISSUE THREAD

**Issue by Del-S** [team-telnyx/telnyx-webrtc-android#306] opened 2023-06-26 10:59 UTC
**Bug Category**
- [x] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [ ] Other

**SDK Version**
implementation 'com.github.team-telnyx:telnyx-webrtc-android:v1.2.20-alpha'

**Describe the bug**
SDK cannot cancel incomming call. It just triggers it again.

**Expected behaviour**
Call is canceled and it will not trigger again.

**To Reproduce**
1. Log on with credentials
2. Call to Telnyx number.
3. Trigger endCall(callId) by the user interface.
4. Call is ended but truggered again.

**Android Device (please complete the following information):**
 - Emulator: AN 13
 - Device: Asus Zenfone 8 (AN 13)

**Logs**
Application receives a call invitation:

```
Invitation(callId=f1680c8c-78f0-4a00-b5c1-9c381ce9b49e, sdp=v=0
	o=FreeSWITCH 1687759542 1687759543 IN IP4 185.246.41.177
	s=FreeSWITCH
	c=IN IP4 185.246.41.177
	t=0 0
	a=msid-semantic: WMS 3FrkRz7aY8FnwLfVYIHlZWV8K9QUGtBz
	m=audio 17098 RTP/SAVPF 0 8
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=fingerprint:sha-256 87:53:CA:62:0C:9F:A1:36:57:F6:6B:B9:86:7F:6E:2B:71:DC:88:AF:60:DD:5C:74:6F:CF:3E:62:A1:CD:39:F4
	a=setup:actpass
	a=rtcp-mux
	a=rtcp:17098 IN IP4 185.246.41.177
	a=ssrc:752388480 cname:YSKFiHG6Fck1NqNB
	a=ssrc:752388480 msid:3FrkRz7aY8FnwLfVYIHlZWV8K9QUGtBz a0
	a=ssrc:752388480 mslabel:3FrkRz7aY8FnwLfVYIHlZWV8K9QUGtBz
	a=ssrc:752388480 label:3FrkRz7aY8FnwLfVYIHlZWV8K9QUGtBza0
	a=ice-ufrag:YkNO6yMHxtr4MSuB
	a=ice-pwd:B46KBDH6FRYi7BKWMnBIMefa
	a=candidate:1586533343 1 udp 2130706431 185.246.41.177 17098 typ host generation 0
	a=candidate:1586533343 2 udp 2130706431 185.246.41.177 17098 typ host generation 0
	a=silenceSupp:off - - - -
	a=ptime:20
	a=sendrecv
	, callerIdName=420732652757, callerIdNumber=420732652757, sessid=a299f101-5a09-48f2-bc2a-99b433de688b))
```
Then the user ends the call
```
[TxSocket] Sending [{
	"id": "b1769a70-f55c-4575-b7ef-c4989d2d8e1d",
	"jsonrpc": "2.0",
	"method": "telnyx_rtc.bye",
	"params": {
		"cause": "USER_BUSY",
		"causeCode": 17,
		"dialogParams": {
		"callId": "f1680c8c-78f0-4a00-b5c1-9c381ce9b49e"
	},
		"sessid": "a299f101-5a09-48f2-bc2a-99b433de688b"
	}
}]
```
After like a second or two the call Invitation is received again with a different call ID.
```
Invitation(callId=d976cf78-568e-4fb1-b11d-f3554cd3356f, sdp=v=0
	o=FreeSWITCH 1687751978 1687751979 IN IP4 185.246.41.177
	s=FreeSWITCH
	c=IN IP4 185.246.41.177
	t=0 0
	a=msid-semantic: WMS xfbLuo9C5wf0nasZki7DkTlhAzQSE8L2
	m=audio 24672 RTP/SAVPF 0 8
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=fingerprint:sha-256 87:53:CA:62:0C:9F:A1:36:57:F6:6B:B9:86:7F:6E:2B:71:DC:88:AF:60:DD:5C:74:6F:CF:3E:62:A1:CD:39:F4
	a=setup:actpass
	a=rtcp-mux
	a=rtcp:24672 IN IP4 185.246.41.177
	a=ssrc:3233024842 cname:eNEy1D0W05Ne653g
	a=ssrc:3233024842 msid:xfbLuo9C5wf0nasZki7DkTlhAzQSE8L2 a0
	a=ssrc:3233024842 mslabel:xfbLuo9C5wf0nasZki7DkTlhAzQSE8L2
	a=ssrc:3233024842 label:xfbLuo9C5wf0nasZki7DkTlhAzQSE8L2a0
	a=ice-ufrag:e0KoJWwamcSRauJe
	a=ice-pwd:7dDYGtLxppBlluspk3EUP0U1
	a=candidate:5771094516 1 udp 2130706431 185.246.41.177 24672 typ host generation 0
	a=candidate:5771094516 2 udp 2130706431 185.246.41.177 24672 typ host generation 0
	a=silenceSupp:off - - - -
	a=ptime:20
	a=sendrecv
	, callerIdName=420732652757, callerIdNumber=420732652757, sessid=a299f101-5a09-48f2-bc2a-99b433de688b))
```

Here is a video:

https://github.com/team-telnyx/telnyx-webrtc-android/assets/6782137/fbdecc50-4eef-43c4-a120-a9742468e978

1) I start the app.
2) I call from my number to Telnyx.
3) App registers a call and shows the call screen.
4) I cancel the call.
5) After few seconds app registers the same call again and shows the call screen.
6) I cancel the call again.
7) After few seconds a call is finished with "User is not available at the moment" message. Note that the top green call notification disapears after some time after the second decline call click.

**Comment by Del-S** [comment] 2023-07-07 10:51
So I tried `1.2.21-alpha` and I am still not able to terminate incomming call.

// Invitation
```
2023-07-07 12:43:23.519
Invitation(callId=7214361f-520b-4cc9-bc25-6907657e0767, sdp=v=0
	o=FreeSWITCH 1688709252 1688709253 IN IP4 185.246.41.177
	s=FreeSWITCH
	c=IN IP4 185.246.41.177
	t=0 0
	a=msid-semantic: WMS XmlmQqSMN735URbQNa0H7CQcQeWbXc3K
	m=audio 17352 RTP/SAVPF 0 8
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=fingerprint:sha-256 87:53:CA:62:0C:9F:A1:36:57:F6:6B:B9:86:7F:6E:2B:71:DC:88:AF:60:DD:5C:74:6F:CF:3E:62:A1:CD:39:F4
	a=setup:actpass
	a=rtcp-mux
	a=rtcp:17352 IN IP4 185.246.41.177
	a=ssrc:731387260 cname:peW6vFJ9DC4nk63X
	a=ssrc:731387260 msid:XmlmQqSMN735URbQNa0H7CQcQeWbXc3K a0
	a=ssrc:731387260 mslabel:XmlmQqSMN735URbQNa0H7CQcQeWbXc3K
	a=ssrc:731387260 label:XmlmQqSMN735URbQNa0H7CQcQeWbXc3Ka0
	a=ice-ufrag:7Tv5mc73gU43XXEd
	a=ice-pwd:2r9oWInpbiDlfw9cgv7sx5lD
	a=candidate:9902103624 1 udp 2130706431 185.246.41.177 17352 typ host generation 0
	a=candidate:9902103624 2 udp 2130706431 185.246.41.177 17352 typ host generation 0
	a=silenceSupp:off - - - -
	a=ptime:20
	a=sendrecv
	, callerIdName=420732652757, callerIdNumber=420732652757, sessid=e1ea2fca-9d09-4b0a-9fd7-2a1fb7ebf905)
```

Ending the call (caller is still ringing after the call was ended in the app btw):

```
2023-07-07 12:43:25.690
[TxSocket] Sending [{
	"id": "9ec3fed3-0b81-4bed-a935-831fe765edb3",
	"jsonrpc": "2.0",
	"method": "telnyx_rtc.bye",
	"params": {
		"cause": "USER_BUSY",
		"causeCode": 17,
		"dialogParams": {
		"callId": "7214361f-520b-4cc9-bc25-6907657e0767"
	},
		"sessid": "e1ea2fca-9d09-4b0a-9fd7-2a1fb7ebf905"
	}
}]
```

Got another invitation (3 seconds later):

```
2023-07-07 12:43:28.182
Invitation(callId=bf092e5c-8e1e-49b1-b5cd-93c238edf78b, sdp=v=0
	o=FreeSWITCH 1688696534 1688696535 IN IP4 185.246.41.177
	s=FreeSWITCH
	c=IN IP4 185.246.41.177
	t=0 0
	a=msid-semantic: WMS UE3GjedfZl9UMDeEr8IZuFVtiXeHL56w
	m=audio 30074 RTP/SAVPF 0 8
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=fingerprint:sha-256 87:53:CA:62:0C:9F:A1:36:57:F6:6B:B9:86:7F:6E:2B:71:DC:88:AF:60:DD:5C:74:6F:CF:3E:62:A1:CD:39:F4
	a=setup:actpass
	a=rtcp-mux
	a=rtcp:30074 IN IP4 185.246.41.177
	a=ssrc:731387264 cname:A02J45OUgOETiJoz
	a=ssrc:731387264 msid:UE3GjedfZl9UMDeEr8IZuFVtiXeHL56w a0
	a=ssrc:731387264 mslabel:UE3GjedfZl9UMDeEr8IZuFVtiXeHL56w
	a=ssrc:731387264 label:UE3GjedfZl9UMDeEr8IZuFVtiXeHL56wa0
	a=ice-ufrag:IXp2samBYq8Am5WM
	a=ice-pwd:VOlQJ0AQF5ANEPdcCs5Vthnh
	a=candidate:5529279633 1 udp 2130706431 185.246.41.177 30074 typ host generation 0
	a=candidate:5529279633 2 udp 2130706431 185.246.41.177 30074 typ host generation 0
	a=silenceSupp:off - - - -
	a=ptime:20
	a=sendrecv
	, callerIdName=420732652757, callerIdNumber=420732652757, sessid=e1ea2fca-9d09-4b0a-9fd7-2a1fb7ebf905))
```

**Comment by isaacakakpo1** [comment] 2023-07-09 10:46
Hello @Del-S Thanks for reporting the issue with sdk version `1.2.21-alpha` . I'll need a few clarifications to properly debug and reproduce the issue. 

1. Is the callee and caller on the same device ? (If yes, try using two separate devices)
2. Is the call ended on the sdk side or from the default phone app. 

With regards to the `call end` crash, does this happen when you repetitively click the end call button (i.e end call right after you place it without it ringing on the other side) ? (If yes we're working on a  fix for this as this is a native crash).

Lastly, we will try to reproduce the issue with different call id's for the same call in push notifications. This shouldn't happen if it's for the same call. 

Thanks again @Del-S

**Comment by Del-S** [comment] 2023-07-10 12:01
Hey. So it seems to work better now. I can finish the calls when I use the app. But I have a problem when I create a call using the FCM notification. #310 

Closing this because it seems to work properly now.

**Comment by Del-S** [comment] 2023-07-10 12:53
Yeah I gonna reopen this since it still happens. But I believe all of the issues we are experiencing are connected to different call ids. So fix that and I think most of the issues will be fixed.

@isaacakakpo1 Thank you for the info.

1) I have an emulator with the application using telnyx and a real device with SIM that is creating the calls to the telnyx. And emulator creates outgoing calls to the device with SIM. So I have two devices one virtual with the telnyx and one real withtout it.
2) Call is ended from the SDK side. Ending from the SIM side seems to work fine.

Call end crash is described here. Basically you can experience it by multiple clicking or ending calls with all the call ids you received. Viz issue: #310.

Call id for the same call changes in almost every case. I guess the best one is here: https://github.com/team-telnyx/telnyx-webrtc-android/issues/309#issuecomment-1628869837 where I received 3 calls ids from 2 sources for one call:
1) FCM: "call_id":"f5734ad0-6b5a-4771-bfee-e6ff2074ccd5".
2) Then I logged into Telnyx.
3) Socket: callId=bc9e2b2c-dfef-4495-bfd9-b280df4deb2d.
4) FCM again: "call_id":"e8cde4da-48cc-4e36-93bf-21eb1c0bdea1".

So at this point we have 3 call IDs and we have no idea which one is correct. :shrug:

**Comment by Del-S** [comment] 2023-08-23 12:58
Well it still happens. Using a socket:
Got an invitation:

```
2023-08-23 14:49:35.613 ReceivedMessageBody(method=telnyx_rtc.invite, result=InviteResponse(callId=6a2fc8ad-d7ec-4a88-a1f9-24be7f0307b6, sdp=v=0
	o=FreeSWITCH 1692777671 1692777672 IN IP4 185.246.41.178
	s=FreeSWITCH
	c=IN IP4 185.246.41.178
	t=0 0
	a=msid-semantic: WMS nd7PTDmR6wOnyJQds0dh9TD6pHnnY8tc
	m=audio 17306 RTP/SAVPF 0 8
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=fingerprint:sha-256 25:1B:DB:C9:74:97:AD:E8:AE:E3:66:71:6A:AC:24:BF:BF:DE:AC:B6:7E:55:D8:C7:77:2B:AE:14:11:57:2F:B9
	a=setup:actpass
	a=rtcp-mux
	a=rtcp:17306 IN IP4 185.246.41.178
	a=ssrc:3241435697 cname:brSUV4CSrh6PRMS9
	a=ssrc:3241435697 msid:nd7PTDmR6wOnyJQds0dh9TD6pHnnY8tc a0
	a=ssrc:3241435697 mslabel:nd7PTDmR6wOnyJQds0dh9TD6pHnnY8tc
	a=ssrc:3241435697 label:nd7PTDmR6wOnyJQds0dh9TD6pHnnY8tca0
	a=ice-ufrag:DVhDEKzTiM66Lq9N
	a=ice-pwd:ISyuM0c388JPLrOfdWIHw7rE
	a=candidate:3704604270 1 udp 2130706431 185.246.41.178 17306 typ host generation 0
	a=candidate:3704604270 2 udp 2130706431 185.246.41.178 17306 typ host generation 0
	a=silenceSupp:off - - - -
	a=ptime:20
	a=sendrecv
	, callerIdName=+420732652757, callerIdNumber=+420732652757, sessid=97fd001a-8bbc-4c03-b6f7-427f53d11966))
```

Ended the call:

```
2023-08-23 14:49:44.491 [TxSocket] Sending [{
	"id": "ae306d5c-9efb-46a7-ad24-e6de17e5c1ff",
	"jsonrpc": "2.0",
	"method": "telnyx_rtc.bye",
	"params": {
		"cause": "USER_BUSY",
		"causeCode": 17,
		"dialogParams": {
		"callId": "6a2fc8ad-d7ec-4a88-a1f9-24be7f0307b6"
	},
		"sessid": "97fd001a-8bbc-4c03-b6f7-427f53d11966"
	}
}]

// End call confirmed:
2023-08-23 14:49:44.534 [TxSocket] Receiving [{"jsonrpc":"2.0","id":"ae306d5c-9efb-46a7-ad24-e6de17e5c1ff","result":{"callID":"6a2fc8ad-d7ec-4a88-a1f9-24be7f0307b6","sip_call_id":"fc12bac6-5c30-4b39-806a-a03828870698","message":"CALL ENDED","causeCode":17,"cause":"USER_BUSY","sessid":"97fd001a-8bbc-4c03-b6f7-427f53d11966"}}]
```

Got the invitation for the same call again after ending it:

```
2023-08-23 14:49:46.515 ReceivedMessageBody(method=telnyx_rtc.invite, result=InviteResponse(callId=9494d905-84bd-4445-a296-dbd38973b67d, sdp=v=0
	o=FreeSWITCH 1692763234 1692763235 IN IP4 185.246.41.178
	s=FreeSWITCH
	c=IN IP4 185.246.41.178
	t=0 0
	a=msid-semantic: WMS 0bsavCZM8yLubA4JgFJwvtQx3Xrmv1Wl
	m=audio 31754 RTP/SAVPF 0 8
	a=rtpmap:0 PCMU/8000
	a=rtpmap:8 PCMA/8000
	a=fingerprint:sha-256 25:1B:DB:C9:74:97:AD:E8:AE:E3:66:71:6A:AC:24:BF:BF:DE:AC:B6:7E:55:D8:C7:77:2B:AE:14:11:57:2F:B9
	a=setup:actpass
	a=rtcp-mux
	a=rtcp:31754 IN IP4 185.246.41.178
	a=ssrc:2041409868 cname:2emnGb0FABZC2Ub9
	a=ssrc:2041409868 msid:0bsavCZM8yLubA4JgFJwvtQx3Xrmv1Wl a0
	a=ssrc:2041409868 mslabel:0bsavCZM8yLubA4JgFJwvtQx3Xrmv1Wl
	a=ssrc:2041409868 label:0bsavCZM8yLubA4JgFJwvtQx3Xrmv1Wla0
	a=ice-ufrag:qLvL5c8YZqblhXxa
	a=ice-pwd:2JoyLe4cGUFyEHxUiSwdUv2K
	a=candidate:9308356891 1 udp 2130706431 185.246.41.178 31754 typ host generation 0
	a=candidate:9308356891 2 udp 2130706431 185.246.41.178 31754 typ host generation 0
	a=silenceSupp:off - - - -
	a=ptime:20
	a=sendrecv
	, callerIdName=+420732652757, callerIdNumber=+420732652757, sessid=97fd001a-8bbc-4c03-b6f7-427f53d11966))
```

Ending it for the second time finally worked.

**Comment by isaacakakpo1** [comment] 2023-10-12 10:49
Hello @Del-S , can you verify if this issue is fixed in release 
https://github.com/team-telnyx/telnyx-webrtc-android/releases/tag/1.2.6

**Comment by Del-S** [comment] 2023-11-21 11:17
Ok so I tested it and it looks better on callee side (in the app) but there is still an issue on the caller side. I got the call invitation:

```
[TxSocket] Receiving [{"jsonrpc":"2.0","id":42849,"method":"telnyx_rtc.invite","params":{"callID":"fdccc25a-d664-4e90-8fe0-76a8b0dea2b6","variables":{"Event-Name":"CHANNEL_DATA","Core-UUID":"49cc4bcb-479f-4a56-a72d-dd4dd3c99a2a","FreeSWITCH-Hostname":"b2bua-rtc.tel-ld6-ibm-prod-367","FreeSWITCH-Switchname":"b2bua-rtc.tel-ld6-ibm-prod-367","FreeSWITCH-IPv4":"10.31.17.80","FreeSWITCH-IPv6":"::1","Event-Date-Local":"2023-11-21 11:10:25","Event-Date-GMT":"Tue, 21 Nov 2023 11:10:25 GMT","Event-Date-Timestamp":"1700565025027067","Event-Calling-File":"switch_channel.c","Event-Calling-Function":"switch_channel_get_variables_prefix","Event-Calling-Line-Number":"4631","Event-Sequence":"111598"},"sdp":"v=0\r\no=FreeSWITCH 1700539669 1700539670 IN IP4 185.246.41.182\r\ns=FreeSWITCH\r\nc=IN IP4 185.246.41.182\r\nt=0 0\r\na=msid-semantic: WMS Lcc9w4wmweHusf74hmxYGh7oFIWJXj3y\r\nm=audio 25356 RTP/SAVPF 0 8 102\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:102 opus/48000/2\r\na=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40\r\na=fingerprint:sha-256 2B:A8:8D:1A:E5:02:29:BA:9A:58:86:72:86:7E:FE:6E:7F:E0:CA:E9:A2:E5:F9:0C:E7:EA:8D:E1:9B:D6:1C:92\r\na=setup:actpass\r\na=rtcp-mux\r\na=rtcp:25356 IN IP4 185.246.41.182\r\na=ssrc:3648736001 cname:l6yI1UUnYsHhxFcF\r\na=ssrc:3648736001 msid:Lcc9w4wmweHusf74hmxYGh7oFIWJXj3y a0\r\na=ssrc:3648736001 mslabel:Lcc9w4wmweHusf74hmxYGh7oFIWJXj3y\r\na=ssrc:3648736001 label:Lcc9w4wmweHusf74hmxYGh7oFIWJXj3ya0\r\na=ice-ufrag:SztoHqDcYpLLzFaL\r\na=ice-pwd:Bzjsj3F8mdgJJifrIyFfO8hD\r\na=candidate:9624645701 1 udp 2130706431 185.246.41.182 25356 typ host generation 0\r\na=candidate:9624645701 2 udp 2130706431 185.246.41.182 25356 typ host generation 0\r\na=silenceSupp:off - - - -\r\na=ptime:20\r\na=sendrecv\r\nm=video 25358 RTP/SAVPF 103\r\nb=AS:1024\r\na=rtpmap:103 VP8/90000\r\na=mid:video\r\na=sendrecv\r\na=fingerprint:sha-256 2B:A8:8D:1A:E5:02:29:BA:9A:58:86:72:86:7E:FE:6E:7F:E0:CA:E9:A2:E5:F9:0C:E7:EA:8D:E1:9B:D6:1C:92\r\na=setup:actpass\r\na=rtcp-mux\r\na=rtcp:25358 IN IP4 185.246.41.182\r\na=rtcp-fb:103 ccm fir\r\na=rtcp-fb:103 ccm tmmbr\r\na=rtcp-fb:103 nack\r\na=rtcp-fb:103 nack pli\r\na=ssrc:2798475336 cname:l6yI1UUnYsHhxFcF\r\na=ssrc:2798475336 msid:Lcc9w4wmweHusf74hmxYGh7oFIWJXj3y v0\r\na=ssrc:2798475336 mslabel:Lcc9w4wmweHusf74hmxYGh7oFIWJXj3y\r\na=ssrc:2798475336 label:Lcc9w4wmweHusf74hmxYGh7oFIWJXj3yv0\r\na=ice-ufrag:ypbRTOlryqyqAWR8\r\na=ice-pwd:PokI30QrLB3DClZ1A1IkFUC4\r\na=candidate:8045209154 1 udp 2130706431 185.246.41.182 25358 typ host generation 0\r\na=candidate:8045209154 2 udp 2130706430 185.246.41.182 25358 typ host generation 0\r\na=end-of-candidates\r\n","caller_id_name":"420732652757","caller_id_number":"420732652757","callee_id_name":"Outbound Call","callee_id_number":"davidSucharda","telnyx_session_id":"91bf9452-885e-11ee-ae65-02420a1f1069","telnyx_leg_id":"91c60030-885e-11ee-8f2c-02420a1f1069","display_direction":"outbound","dialogParams":{"custom_headers":[]}}}]
```

I then used the app to end the call.

```
[TxSocket] Receiving [{"jsonrpc":"2.0","id":42892,"method":"telnyx_rtc.bye","params":{"callID":"fdccc25a-d664-4e90-8fe0-76a8b0dea2b6","sip_call_id":"","sipCode":487,"sipReason":"Request Terminated","causeCode":487,"cause":"ORIGINATOR_CANCEL","dialogParams":{"custom_headers":[]}}}]
```
- I never got the call again in the app which is great. 
- But the caller kept calling, it never terminated the call on the caller side.

**Comment by isaacakakpo1** [comment] 2023-11-21 11:31
That's good progress @Del-S, In the case of receiving  `telnyx_rtc.bye` it is safe to end the call on the caller side as well (app side). Can you confirm if the caller is an app as well ?

**Comment by isaacakakpo1** [comment] 2023-11-21 12:46
Right Understood. This seems to be a vendor/provider issue when ending calls originating from the native/system call app. I'll keep you posted on this.

**Comment by Del-S** [comment] 2023-11-28 12:01
@isaacakakpo1 So I have one more issue with ending the call. It might be connected to the vendor issue we already talked about. It happens in a situation when I terminate Socket connection to Telnyx. So basically:

1) I call the app. It handles the notification correctly and shows the call.
2) I end the call in the app, but caller is still calling (vendor issue).
3) I kill the app (close the connection to the socket).
4) I receive FCM notification for the call again.

Note that once I end the call from point 4) I do not receive any more FCM notifications. Expected behavior is that I do not receive the FCM notification. Can you somehow make it that call ended from the socket also does not send the notification?

Side note: I guess that if the vendor also finished the call I would not receive the notification but that should not matter in this case. We do not want to rely on the vendor but on Telnyx. :)

**Closed** 2023-11-28 12:16 UTC
Labels: bug
