### ISSUE TITLE
[Bug] The called party has no sound

### ISSUE THREAD

**Issue by ShiXiaoXiang2019** [team-telnyx/telnyx-webrtc-android#127] opened 2022-01-18 07:17 UTC
**Bug Category**
- [x] Credential Login

**SDK Version**
Demo zip downloaded on January 18

**Describe the bug**
After the first installation, the call is completed and connected, everything is normal and the call is closed. After the second call and connected, the called party has no sound

**Expected behaviour**
After the call is connected, both the calling party and the called party can hear each other's voice

**To Reproduce**
Steps to reproduce the behaviour:
After logging in with on-demand credentials, call + 12082544968. After the called party answers, both parties can talk normally, and can get the voice. Hang up the call. For the second call, after the called party answers, the calling party can get the voice of the other party, but the called party cannot hear the voice

**Android Device ():**
 - Emulator: (true)
 - Android Device: Real machine test Samsung Galaxy S8 SM-G950U
 - Android Version: Android 9

**Logs**

GMT+8

2022-01-18 15:12:01.082 27338-27397/com.telnyx.webrtc.sdk D/TelnyxClient$networkCallback: [TelnyxClient] :: There is a network available
2022-01-18 15:12:02.246 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Connection established :: rtc.telnyx.com
2022-01-18 15:12:02.247 27338-27406/com.telnyx.webrtc.sdk D/TelnyxClient: [TelnyxClient] :: onConnectionEstablished
2022-01-18 15:12:02.270 27338-27338/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Sending [{"id":"30155a06-9ed8-461d-ad4b-6f08b1dc7909","jsonrpc":"2.0","method":"login","params":{"login":"gencredmTes1z2Ocsd0hwPHoxu4enRyF8IJpUTzZ7opJEnHQp","loginParams":[],"passwd":"ec28bd8ac2c644f1a71fb1ca86996f68","userVariables":{"push_device_token":"eYcYgYd7RsS81yNaCKz-sq:APA91bEF-KUQIFnyXCBgFrIyZxe6zTPoHROPn5YNSiC8e8JsFkvCdGe7Tl1ExwLoocOF7_611sKGfr0BvyAEkzCgZx6wAJyAlrMz7Defi-MEGEdhsetkruG3iU0zchLelY9lDW4CpvUJ","push_notification_provider":"android"}}}]
2022-01-18 15:12:02.459 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":"30155a06-9ed8-461d-ad4b-6f08b1dc7909","result":{"message":"logged in","sessid":"437fea8f-6033-4633-9bbb-40d55e236ccd"}}]
2022-01-18 15:12:02.510 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":3084,"method":"telnyx_rtc.clientReady","params":{"reattached_sessions":[]}}]
2022-01-18 15:12:02.512 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Received Method [telnyx_rtc.clientReady]
2022-01-18 15:12:02.513 27338-27406/com.telnyx.webrtc.sdk D/TelnyxClient: [TelnyxClient] :: onClientReady :: retrieving gateway state
2022-01-18 15:12:02.515 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Sending [{"id":"48007fa2-3cb9-4ee4-934c-72453239748a","jsonrpc":"2.0","method":"telnyx_rtc.gatewayState","params":{}}]
2022-01-18 15:12:02.708 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":"48007fa2-3cb9-4ee4-934c-72453239748a","result":{"params":{"state":"REGED"},"sessid":"437fea8f-6033-4633-9bbb-40d55e236ccd"}}]
2022-01-18 15:12:02.716 27338-27406/com.telnyx.webrtc.sdk D/TelnyxClient: [TelnyxClient] :: onLoginSuccessful :: [437fea8f-6033-4633-9bbb-40d55e236ccd] :: Ready to make calls
2022-01-18 15:12:03.979 27338-27338/com.telnyx.webrtc.sdk D/TelnyxClient: ringtone/ringback media player stopped and released
2022-01-18 15:12:04.151 27338-27425/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Sending [{"id":"57427ba2-13e6-48dd-a7d5-1a37ea928afc","jsonrpc":"2.0","method":"telnyx_rtc.invite","params":{"dialogParams":{"attach":false,"audio":true,"callID":"0d43d066-e1ff-4996-bb2b-cb2d5d0a6ef2","caller_id_name":"alice","caller_id_number":"+12142866127","clientState":"U2FtcGxlIENsaWVudCBTdGF0ZQ\u003d\u003d\n","destination_number":"+12082544968","remote_caller_id_name":"","screenShare":false,"useStereo":false,"userVariables":[],"video":false},"sdp":"v\u003d0\r\no\u003d- 4874457196128902914 2 IN IP4 127.0.0.1\r\ns\u003d-\r\nt\u003d0 0\r\na\u003dgroup:BUNDLE audio\r\na\u003dmsid-semantic: WMS audio_local_stream\r\nm\u003daudio 35377 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc\u003dIN IP4 192.168.1.105\r\na\u003drtcp:9 IN IP4 0.0.0.0\r\na\u003dcandidate:2222700650 1 udp 2122260223 192.168.1.105 35377 typ host generation 0 network-id 4 network-cost 10\r\na\u003dcandidate:314413345 1 udp 2122194687 26.26.26.21 49765 typ host generation 0 network-id 3 network-cost 50\r\na\u003dcandidate:559267639 1 udp 2122136831 ::1 48633 typ host generation 0 network-id 2\r\na\u003dcandidate:1510613869 1 udp 2122063615 127.0.0.1 37619 typ host generation 0 network-id 1\r\na\u003dcandidate:3405268122 1 tcp 1518280447 192.168.1.105 50576 typ host tcptype passive generation 0 network-id 4 network-cost 10\r\na\u003dcandidate:1547595217 1 tcp 1518214911 26.26.26.21 36188 typ host tcptype passive generation 0 network-id 3 network-cost 50\r\na\u003dcandidate:1876313031 1 tcp 1518157055 ::1 57249 typ host tcptype passive generation 0 network-id 2\r\na\u003dcandidate:344579997 1 tcp 1518083839 127.0.0.1 49808 typ host tcptype passive generation 0 network-id 1\r\na\u003dice-ufrag:BMf8\r\na\u003dice-pwd:Lq57Zq614kZX8W7s0yC7QADx\r\na\u003dice-options:trickle renomination\r\na\u003dfingerprint:sha-256 12:B9:07:B3:68:98:36:F7:B3:19:95:4A:FD:4E:40:A9:15:62:51:B6:8B:42:51:A4:AC:00:A7:F1:D4:40:F9:8B\r\na\u003dsetup:actpass\r\na\u003dmid:audio\r\na\u003dextmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na\u003dextmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na\u003dextmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na\u003dsendrecv\r\na\u003drtcp-mux\r\na\u003drtpmap:111 opus/48000/2\r\na\u003drtcp-fb:111 transport-cc\r\na\u003dfmtp:111 minptime\u003d10;useinbandfec\u003d1\r\na\u003drtpmap:103 ISAC/16000\r\na\u003drtpmap:104 ISAC/32000\r\na\u003drtpmap:9 G722/8000\r\na\u003drtpmap:102 ILBC/8000\r\na\u003drtpmap:0 PCMU/8000\r\na\u003drtpmap:8 PCMA/8000\r\na\u003drtpmap:106 CN/32000\r\na\u003drtpmap:105 CN/16000\r\na\u003drtpmap:13 CN/8000\r\na\u003drtpmap:110 telephone-event/48000\r\na\u003drtpmap:112 telephone-event/32000\r\na\u003drtpmap:113 telephone-event/16000\r\na\u003drtpmap:126 telephone-event/8000\r\na\u003dssrc:3717374036 cname:TH6PCEL4ZEcY1ZL4\r\na\u003dssrc:3717374036 msid:audio_local_stream audio_local_track\r\na\u003dssrc:3717374036 mslabel:audio_local_stream\r\na\u003dssrc:3717374036 label:audio_local_track\r\n","sessionId":"437fea8f-6033-4633-9bbb-40d55e236ccd","User-Agent":"Android-1.0"}}]
2022-01-18 15:12:04.352 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":"57427ba2-13e6-48dd-a7d5-1a37ea928afc","result":{"message":"CALL CREATED","callID":"0d43d066-e1ff-4996-bb2b-cb2d5d0a6ef2","sessid":"437fea8f-6033-4633-9bbb-40d55e236ccd"}}]
2022-01-18 15:12:05.521 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":3087,"method":"telnyx_rtc.ringing","params":{"callID":"0d43d066-e1ff-4996-bb2b-cb2d5d0a6ef2","caller_id_name":"alice","caller_id_number":"+12142866127","callee_id_name":"Outbound Call","callee_id_number":"+12082544968","telnyx_session_id":"f07e4b66-782d-11ec-8b8f-02420a0d5b68","telnyx_leg_id":"f07e38d8-782d-11ec-b440-02420a0d5b68","display_direction":"inbound"}}]
2022-01-18 15:12:05.524 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Received Method [telnyx_rtc.ringing]
2022-01-18 15:12:05.527 27338-27406/com.telnyx.webrtc.sdk D/TelnyxClient: [TelnyxClient] :: onRingingReceived [{"jsonrpc":"2.0","id":3087,"method":"telnyx_rtc.ringing","params":{"callID":"0d43d066-e1ff-4996-bb2b-cb2d5d0a6ef2","caller_id_name":"alice","caller_id_number":"+12142866127","callee_id_name":"Outbound Call","callee_id_number":"+12082544968","telnyx_session_id":"f07e4b66-782d-11ec-8b8f-02420a0d5b68","telnyx_leg_id":"f07e38d8-782d-11ec-b440-02420a0d5b68","display_direction":"inbound"}}]
2022-01-18 15:12:06.554 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":3088,"method":"telnyx_rtc.media","params":{"callID":"0d43d066-e1ff-4996-bb2b-cb2d5d0a6ef2","sdp":"v=0\r\no=FreeSWITCH 1642463911 1642463912 IN IP4 103.115.244.151\r\ns=FreeSWITCH\r\nc=IN IP4 103.115.244.151\r\nt=0 0\r\na=msid-semantic: WMS DGjs77skoYXoBEtOqvTV46YXcub5lZSP\r\nm=audio 26014 UDP/TLS/RTP/SAVPF 111 110\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 useinbandfec=1; minptime=10\r\na=rtpmap:110 telephone-event/48000\r\na=silenceSupp:off - - - -\r\na=ptime:20\r\na=sendrecv\r\na=mid:audio\r\na=fingerprint:sha-256 71:56:1E:99:86:EA:3F:17:36:FD:38:C8:F5:90:B8:55:C0:8E:6B:8B:34:B8:A5:10:E0:DB:A2:51:0D:E2:47:AF\r\na=setup:active\r\na=rtcp-mux\r\na=rtcp:26014 IN IP4 103.115.244.151\r\na=ice-ufrag:72Z1YNP08RWjGEY2\r\na=ice-pwd:wWnmcSqgaILYjU1gNR8CuOts\r\na=candidate:7630078012 1 udp 2130706431 103.115.244.151 26014 typ host generation 0\r\na=end-of-candidates\r\na=ssrc:1911013171 cname:w17uZpEedssFXLjd\r\na=ssrc:1911013171 msid:DGjs77skoYXoBEtOqvTV46YXcub5lZSP a0\r\na=ssrc:1911013171 mslabel:DGjs77skoYXoBEtOqvTV46YXcub5lZSP\r\na=ssrc:1911013171 label:DGjs77skoYXoBEtOqvTV46YXcub5lZSPa0\r\n"}}]
2022-01-18 15:12:06.573 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Received Method [telnyx_rtc.media]
2022-01-18 15:12:12.055 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":3089,"method":"telnyx_rtc.answer","params":{"callID":"0d43d066-e1ff-4996-bb2b-cb2d5d0a6ef2"}}]
2022-01-18 15:12:12.067 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Received Method [telnyx_rtc.answer]
2022-01-18 15:12:12.130 27338-27406/com.telnyx.webrtc.sdk D/TelnyxClient: ringtone/ringback media player stopped and released
2022-01-18 15:12:31.496 27338-27338/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Sending [{"id":"a80b2f0e-1a02-4755-882a-f152085e22cd","jsonrpc":"2.0","method":"telnyx_rtc.bye","params":{"cause":"USER_BUSY","causeCode":1,"dialogParams":{"callId":"0d43d066-e1ff-4996-bb2b-cb2d5d0a6ef2"},"sessionId":"437fea8f-6033-4633-9bbb-40d55e236ccd"}}]
2022-01-18 15:12:31.498 27338-27338/com.telnyx.webrtc.sdk D/TelnyxClient: ringtone/ringback media player stopped and released
2022-01-18 15:12:31.688 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":"a80b2f0e-1a02-4755-882a-f152085e22cd","result":{"callID":"0d43d066-e1ff-4996-bb2b-cb2d5d0a6ef2","sip_call_id":"eaeb7203-3824-449b-a4a6-f60dc02694e5","message":"CALL ENDED","causeCode":17,"cause":"USER_BUSY","sessid":"437fea8f-6033-4633-9bbb-40d55e236ccd"}}]
2022-01-18 15:12:33.822 27338-27338/com.telnyx.webrtc.sdk D/TelnyxClient: ringtone/ringback media player stopped and released
2022-01-18 15:12:34.106 27338-27483/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Sending [{"id":"354e7359-1b88-4fd7-8f7c-5548de0a208e","jsonrpc":"2.0","method":"telnyx_rtc.invite","params":{"dialogParams":{"attach":false,"audio":true,"callID":"c63e1f5c-51a0-434d-82c8-9b7b8de06226","caller_id_name":"alice","caller_id_number":"+12142866127","clientState":"U2FtcGxlIENsaWVudCBTdGF0ZQ\u003d\u003d\n","destination_number":"+12082544968","remote_caller_id_name":"","screenShare":false,"useStereo":false,"userVariables":[],"video":false},"sdp":"v\u003d0\r\no\u003d- 4398966707657479932 2 IN IP4 127.0.0.1\r\ns\u003d-\r\nt\u003d0 0\r\na\u003dgroup:BUNDLE audio\r\na\u003dmsid-semantic: WMS audio_local_stream\r\nm\u003daudio 47364 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc\u003dIN IP4 192.168.1.105\r\na\u003drtcp:9 IN IP4 0.0.0.0\r\na\u003dcandidate:2222700650 1 udp 2122260223 192.168.1.105 47364 typ host generation 0 network-id 4 network-cost 10\r\na\u003dcandidate:314413345 1 udp 2122194687 26.26.26.21 45100 typ host generation 0 network-id 3 network-cost 50\r\na\u003dcandidate:559267639 1 udp 2122136831 ::1 37784 typ host generation 0 network-id 2\r\na\u003dcandidate:1510613869 1 udp 2122063615 127.0.0.1 41528 typ host generation 0 network-id 1\r\na\u003dcandidate:3405268122 1 tcp 1518280447 192.168.1.105 44209 typ host tcptype passive generation 0 network-id 4 network-cost 10\r\na\u003dcandidate:1547595217 1 tcp 1518214911 26.26.26.21 58634 typ host tcptype passive generation 0 network-id 3 network-cost 50\r\na\u003dcandidate:1876313031 1 tcp 1518157055 ::1 53597 typ host tcptype passive generation 0 network-id 2\r\na\u003dcandidate:344579997 1 tcp 1518083839 127.0.0.1 39045 typ host tcptype passive generation 0 network-id 1\r\na\u003dice-ufrag:csWC\r\na\u003dice-pwd:nBhmjYHml7/QCHXM/jMrr8fV\r\na\u003dice-options:trickle renomination\r\na\u003dfingerprint:sha-256 1F:65:3B:A7:04:6A:EE:CC:45:89:98:64:BC:8F:29:13:50:7F:90:8F:2E:07:89:52:B0:B7:C6:02:BF:1F:7E:28\r\na\u003dsetup:actpass\r\na\u003dmid:audio\r\na\u003dextmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na\u003dextmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na\u003dextmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na\u003dsendrecv\r\na\u003drtcp-mux\r\na\u003drtpmap:111 opus/48000/2\r\na\u003drtcp-fb:111 transport-cc\r\na\u003dfmtp:111 minptime\u003d10;useinbandfec\u003d1\r\na\u003drtpmap:103 ISAC/16000\r\na\u003drtpmap:104 ISAC/32000\r\na\u003drtpmap:9 G722/8000\r\na\u003drtpmap:102 ILBC/8000\r\na\u003drtpmap:0 PCMU/8000\r\na\u003drtpmap:8 PCMA/8000\r\na\u003drtpmap:106 CN/32000\r\na\u003drtpmap:105 CN/16000\r\na\u003drtpmap:13 CN/8000\r\na\u003drtpmap:110 telephone-event/48000\r\na\u003drtpmap:112 telephone-event/32000\r\na\u003drtpmap:113 telephone-event/16000\r\na\u003drtpmap:126 telephone-event/8000\r\na\u003dssrc:4194333168 cname:P1To7fvi4Z9m+7ys\r\na\u003dssrc:4194333168 msid:audio_local_stream audio_local_track\r\na\u003dssrc:4194333168 mslabel:audio_local_stream\r\na\u003dssrc:4194333168 label:audio_local_track\r\n","sessionId":"437fea8f-6033-4633-9bbb-40d55e236ccd","User-Agent":"Android-1.0"}}]
2022-01-18 15:12:34.304 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":"354e7359-1b88-4fd7-8f7c-5548de0a208e","result":{"message":"CALL CREATED","callID":"c63e1f5c-51a0-434d-82c8-9b7b8de06226","sessid":"437fea8f-6033-4633-9bbb-40d55e236ccd"}}]
2022-01-18 15:12:35.515 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":3091,"method":"telnyx_rtc.ringing","params":{"callID":"c63e1f5c-51a0-434d-82c8-9b7b8de06226","caller_id_name":"alice","caller_id_number":"+12142866127","callee_id_name":"Outbound Call","callee_id_number":"+12082544968","telnyx_session_id":"02597310-782e-11ec-a845-02420a0d5b68","telnyx_leg_id":"0259621c-782e-11ec-9056-02420a0d5b68","display_direction":"inbound"}}]
2022-01-18 15:12:35.525 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Received Method [telnyx_rtc.ringing]
2022-01-18 15:12:35.534 27338-27406/com.telnyx.webrtc.sdk D/TelnyxClient: [TelnyxClient] :: onRingingReceived [{"jsonrpc":"2.0","id":3091,"method":"telnyx_rtc.ringing","params":{"callID":"c63e1f5c-51a0-434d-82c8-9b7b8de06226","caller_id_name":"alice","caller_id_number":"+12142866127","callee_id_name":"Outbound Call","callee_id_number":"+12082544968","telnyx_session_id":"02597310-782e-11ec-a845-02420a0d5b68","telnyx_leg_id":"0259621c-782e-11ec-9056-02420a0d5b68","display_direction":"inbound"}}]
2022-01-18 15:12:36.061 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":3092,"method":"telnyx_rtc.media","params":{"callID":"c63e1f5c-51a0-434d-82c8-9b7b8de06226","sdp":"v=0\r\no=FreeSWITCH 1642463125 1642463126 IN IP4 103.115.244.151\r\ns=FreeSWITCH\r\nc=IN IP4 103.115.244.151\r\nt=0 0\r\na=msid-semantic: WMS AakRdwLQhUYJSWEQlPNKwh0k05ZvB3D2\r\nm=audio 26830 UDP/TLS/RTP/SAVPF 111 110\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 useinbandfec=1; minptime=10\r\na=rtpmap:110 telephone-event/48000\r\na=silenceSupp:off - - - -\r\na=ptime:20\r\na=sendrecv\r\na=mid:audio\r\na=fingerprint:sha-256 71:56:1E:99:86:EA:3F:17:36:FD:38:C8:F5:90:B8:55:C0:8E:6B:8B:34:B8:A5:10:E0:DB:A2:51:0D:E2:47:AF\r\na=setup:active\r\na=rtcp-mux\r\na=rtcp:26830 IN IP4 103.115.244.151\r\na=ice-ufrag:18bof2y6XorphVib\r\na=ice-pwd:zS8A3MJ0erEtEZUvYWK4O90C\r\na=candidate:4057180990 1 udp 2130706431 103.115.244.151 26830 typ host generation 0\r\na=end-of-candidates\r\na=ssrc:1911013201 cname:3OJ7blOi6CSOomvA\r\na=ssrc:1911013201 msid:AakRdwLQhUYJSWEQlPNKwh0k05ZvB3D2 a0\r\na=ssrc:1911013201 mslabel:AakRdwLQhUYJSWEQlPNKwh0k05ZvB3D2\r\na=ssrc:1911013201 label:AakRdwLQhUYJSWEQlPNKwh0k05ZvB3D2a0\r\n"}}]
2022-01-18 15:12:36.067 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Received Method [telnyx_rtc.media]
2022-01-18 15:13:14.330 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":3099,"method":"telnyx_rtc.answer","params":{"callID":"c63e1f5c-51a0-434d-82c8-9b7b8de06226"}}]
2022-01-18 15:13:14.334 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Received Method [telnyx_rtc.answer]
2022-01-18 15:13:14.390 27338-27406/com.telnyx.webrtc.sdk D/TelnyxClient: ringtone/ringback media player stopped and released
2022-01-18 15:13:34.648 27338-27338/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Sending [{"id":"fa74c976-173c-44c1-b81a-c04366ac2c20","jsonrpc":"2.0","method":"telnyx_rtc.bye","params":{"cause":"USER_BUSY","causeCode":1,"dialogParams":{"callId":"c63e1f5c-51a0-434d-82c8-9b7b8de06226"},"sessionId":"437fea8f-6033-4633-9bbb-40d55e236ccd"}}]
2022-01-18 15:13:34.650 27338-27338/com.telnyx.webrtc.sdk D/TelnyxClient: ringtone/ringback media player stopped and released
2022-01-18 15:13:34.841 27338-27406/com.telnyx.webrtc.sdk D/VERTO: [TxSocket] Receiving [{"jsonrpc":"2.0","id":"fa74c976-173c-44c1-b81a-c04366ac2c20","result":{"callID":"c63e1f5c-51a0-434d-82c8-9b7b8de06226","sip_call_id":"2e93c706-eb3c-4257-bd8b-181d1436e093","message":"CALL ENDED","causeCode":17,"cause":"USER_BUSY","sessid":"437fea8f-6033-4633-9bbb-40d55e236ccd"}}]

**Comment by Oliver-Zimmerman** [comment] 2022-01-18 17:11
I am investigating this now, will update here tomorrow. Thanks, @ShiXiaoXiang2019

**Comment by Oliver-Zimmerman** [comment] 2022-01-19 10:29
Hi @ShiXiaoXiang2019, can you confirm that you are using the same device that previously made the call to do the call again or does Device A call device B, and then device B calls device B back afterwards.

Also, can you please do a test for me and wait for up to a minute once a call is established to see if the audio can eventually be heard?

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 12:58
A device Samsung g9500 Android 9

B device Samsung g9600 Android 10

A device caller C device callee

In the first normal call, both sides have voices. In the second call, the called party cannot hear the voice (the called party still has no voice after waiting for 1 minute)

B caller C callee

For the first normal call, both sides have voices. For the second call, both sides also have voices (both calls can be heard)


This situation is 100% repeated

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:02
If you need a log, I can provide it to you, but our time zone is inconsistent. My side is the Beijing time zone. I can rest at about 24:00 Beijing time at most. I hope this problem can be solved as soon as possible. There is another problem to be solved later

**Comment by Oliver-Zimmerman** [comment] 2022-01-20 13:04
@ShiXiaoXiang2019 I will look into this now, but it is likely an issue with the sample app rather than the SDK. The sample app is meant to be used as a reference only - the SDK is meant to be used to build your own application.

I currently cannot reproduce this behaviour so I'm not sure what it can be but will continue looking today.

**Comment by Oliver-Zimmerman** [comment] 2022-01-20 13:04
@ShiXiaoXiang2019 Is this still only happening for devices under Android version 9?

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:09
Maybe it's the demo problem. Our development is modified based on your demo. The language he uses is Java and he is not very familiar with kotlin

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:10
Yes, it only happens in Android 9 and below

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:12
I can also use the simulator to reproduce it in Android 9 or below

**Comment by Oliver-Zimmerman** [comment] 2022-01-20 13:12
So you are testing with a modified version of the sample app? Or just the base sample app?

Let me get the test scenario exactly correct:

Device A (Caller A) is an Android 9 device
Device B (Callee B) is an Android 10 device

Device A calls Device B and both voices can be heard. Device B then ends the call.

Device A calls Device B again and no voices can be heard. 

This is the scenario I am testing and it is currently working, can you confirm that it is the correct scenario?

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:23
Your demo runs on the Android 9 device. As the caller, both parties can talk normally for the first time, and the callee can't hear the sound for the second time, but the caller can get the sound,everything is normal on Android 10 devices

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:29
I only modified the contents of your demo Appconstants.KT,

const val MOCK_ USERNAME = "MOCK_ USERNAME"

const val MOCK_ PASSWORD = "MOCK_ PASSWORD"

const val MOCK_ CALLER_ NAME = "alice"

const val MOCK_ CALLER_ NUMBER = "+12142866127"

const val MOCK_ DESTINATION_ NUMBER = "+12082544968"

I used my own username and password

**Comment by Oliver-Zimmerman** [comment] 2022-01-20 13:32
@ShiXiaoXiang2019 just to confirm are you calling mobile to mobile or mobile to web?

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:35
Use your demo to dial my own real number

**Comment by Oliver-Zimmerman** [comment] 2022-01-20 13:37
Okay, so that is a different scenario altogether. I was under the impression you were calling demo to demo. Let me test this scenerio then. 

The demo is calling the real device. All is fine. We put the call down.

The demo calls the real device again, and the demo cannot be heard by real device. Correct?

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:38
Yes, my English is not good, use the translation, ha ha

**Comment by Oliver-Zimmerman** [comment] 2022-01-20 13:41
And is the Android 9 device running the demo app? Or is the Android 9 device the real device?

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 13:43
Android 9 running demo,then dial my own real number

**Comment by ShiXiaoXiang2019** [comment] 2022-01-20 14:09
Can you reproduce my scene? Your demo runs on the real mobile phone of Android 9 and dials my real mobile phone number

**Comment by Oliver-Zimmerman** [comment] 2022-01-20 16:51
@ShiXiaoXiang2019 it took a while but I finally got a scenario that reproduces it. I have opened a bug ticket and will make it my priority. I will update you here

**Comment by ShiXiaoXiang2019** [comment] 2022-01-21 01:50
> 
That's OK. Thank you very much!

**Comment by Oliver-Zimmerman** [comment] 2022-01-24 10:50
@ShiXiaoXiang2019 Just letting you know that we are still looking into this. it seems to only affect Android 9 and below devices, and doesn't appear to be an issue with the SDP that we offer as both calls have an attached audio track. I will keep updating you here.

**Comment by Oliver-Zimmerman** [comment] 2022-01-24 18:55
@ShiXiaoXiang2019 we eventually found the source of the issue and have created a PR. Please see here:
https://github.com/team-telnyx/telnyx-webrtc-android/pull/128

It should be merged so if you would like to test main now and let me know if it is working

**Comment by ShiXiaoXiang2019** [comment] 2022-01-25 06:31
OK, the above problem has been solved

**Comment by ShiXiaoXiang2019** [comment] 2022-01-25 09:09
There's another problem. I don't know how to use Android demo to answer the phone. I bought a number. If an inbound call comes in from this number, how can I notify the android app of an inbound call, and how can I connect this call with Android demo and talk normally

**Comment by Oliver-Zimmerman** [comment] 2022-01-25 09:28
@ShiXiaoXiang2019 Is this a bug? Or have you just not assigned a number to your SIP connection in the portal?

Please go into your Portal, select the numbers tab and assign the number to a SIP connection or app with the connection or app drop down. 

If you still don't have a SIP Connection please follow this guide: https://developers.telnyx.com/docs/v2/webrtc/quickstart

Once a number is assigned to a SIP Connection (not the on demand credentials, the actual SIP connection), and you have logged in with this connection, you will be able to call the number assigned to that connection

I am closing this bug, if this is an actual bug and not a setup issue, please open a new bug with the template.

**Closed by Oliver-Zimmerman** 2022-01-25 09:28 UTC
Labels: bug

**Comment by ShiXiaoXiang2019** [comment] 2022-01-25 09:37
ok,thank you
